extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern Lights1 castle_grounds_dl_Wood_lights;
extern Lights1 castle_grounds_dl_Road_lights;
extern Lights1 castle_grounds_dl_Grass_lights;
extern Lights1 castle_grounds_dl_Black_lights;
extern u8 castle_grounds_dl_Material4_ci8[];
extern u8 castle_grounds_dl_Material4_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_Material2_ci8[];
extern u8 castle_grounds_dl_Material2_ci8_pal_rgba16[];
extern u8 castle_grounds_dl_Material1_ci8[];
extern u8 castle_grounds_dl_Material1_ci8_pal_rgba16[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_0[55];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_1[29];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_2[123];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Plane_mesh_layer_1_vtx_3[12];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1_tri_3[];
extern Gfx mat_castle_grounds_dl_Wood[];
extern Gfx mat_revert_castle_grounds_dl_Wood[];
extern Gfx mat_castle_grounds_dl_Road[];
extern Gfx mat_revert_castle_grounds_dl_Road[];
extern Gfx mat_castle_grounds_dl_Grass[];
extern Gfx mat_revert_castle_grounds_dl_Grass[];
extern Gfx mat_castle_grounds_dl_Black[];
extern Gfx castle_grounds_dl_Plane_mesh_layer_1[];
extern Gfx castle_grounds_dl_material_revert_render_settings[];
