extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern Lights1 bob_dl_Stone_lights;
extern Lights1 bob_dl_Floor_Dirt_lights;
extern Lights1 bob_dl_Floor_Granite_lights;
extern Lights1 bob_dl_Wall_Brown_lights;
extern Lights1 bob_dl_Quick_Sand_lights;
extern u8 bob_dl_Material2_ci8[];
extern u8 bob_dl_Material2_ci8_pal_rgba16[];
extern u8 bob_dl_Material1_ci8[];
extern u8 bob_dl_Material1_ci8_pal_rgba16[];
extern u8 bob_dl_Material6_ci8[];
extern u8 bob_dl_Material6_ci8_pal_rgba16[];
extern u8 bob_dl_Material3_ci8[];
extern u8 bob_dl_Material3_ci8_pal_rgba16[];
extern u8 bob_dl_Material19_ci8[];
extern u8 bob_dl_Material19_ci8_pal_rgba16[];
extern Vtx bob_dl_Rock_Platform_mesh_layer_1_vtx_0[51];
extern Gfx bob_dl_Rock_Platform_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Start_Floor_mesh_layer_1_vtx_0[13];
extern Gfx bob_dl_Start_Floor_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Start_Floor_mesh_layer_1_vtx_1[27];
extern Gfx bob_dl_Start_Floor_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Start_Floor_mesh_layer_1_vtx_2[60];
extern Gfx bob_dl_Start_Floor_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Start_Floor_mesh_layer_1_vtx_3[4];
extern Gfx bob_dl_Start_Floor_mesh_layer_1_tri_3[];
extern Gfx mat_bob_dl_Stone[];
extern Gfx mat_revert_bob_dl_Stone[];
extern Gfx mat_bob_dl_Floor_Dirt[];
extern Gfx mat_revert_bob_dl_Floor_Dirt[];
extern Gfx mat_bob_dl_Floor_Granite[];
extern Gfx mat_revert_bob_dl_Floor_Granite[];
extern Gfx mat_bob_dl_Wall_Brown[];
extern Gfx mat_revert_bob_dl_Wall_Brown[];
extern Gfx mat_bob_dl_Quick_Sand[];
extern Gfx mat_revert_bob_dl_Quick_Sand[];
extern Gfx bob_dl_Rock_Platform_mesh_layer_1[];
extern Gfx bob_dl_Start_Floor_mesh_layer_1[];
extern Gfx bob_dl_material_revert_render_settings[];
